# -*- coding: utf-8 -*-
"""Loading Data and Viewing Data (External resource).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bKwJO41C4PwV8usK6mItcuAhlpb3zQDn
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install pyarrow

import pandas as pd

url_xlsx = 'https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/n9LOuKI9SlUa1b5zkaCMeg/Product-sales.xlsx'
df = pd.read_excel (url_xlsx, engine='openpyxl')
df.head()

df.rename(columns={'CustomerCity':'CusCity'})

